# Generated by Django 2.1.7 on 2019-02-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='anime_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
