# Generated by Django 2.1.7 on 2019-03-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190331_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(db_column='ユーザー名', max_length=50, unique=True, verbose_name='nick name'),
        ),
    ]
