# Generated by Django 2.1.7 on 2019-04-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190410_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='anime_id',
        ),
    ]
