# Generated by Django 2.1.7 on 2019-02-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='context',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='post_date',
            new_name='posted_date',
        ),
    ]
